### ISSUE TITLE
Getting a wrong LogGroupName

### ISSUE THREAD

**Issue by ckho-wkcda** [coyoteecd/serverless-api-gateway-execution-log-manager#1]
The current approach of getting LogGroupName will obtain the first whatever log group of the same stage, but may not be the log group of the exact api gateway deployed.

To fix the issue, we have to find another way to obtain the api gateway ID.

**Comment by coyoteecd** [comment]
I guess it would be possible to take the API gateway ID as stack output, given that the plugin runs after deploy.
If you have a PR with an improved detection, I'd be happy to include it.

As a general idea, this plugin was a stop-gap measure to adjust retention of our logs.
A better solution is to submit a PR against Serverless Framework repo that creates the execution log group as a stack resource (as part of the deployed stack template, meaning you can reference the API gateway ID), in the hope that API Gateway will find the log group and write logs to it. 

This automatically solves the cleanup portion too; if the log group is part of the stack, it will get deleted on stack removal.
